services:
  app_db:
    container_name: DrinkinggameDB
    image: mariadb:10.8.2
    environment:
      MYSQL_DATABASE: drinkinggame
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes: 
      - mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    networks: 
    - app-network 
    restart: unless-stopped
  app-backend:
    container_name: AppBackend
    image: ghcr.io/dasanten/yourdrinkinggame:master
    environment:
      - ACTIVE_PROFILE=prod
      - DATABASE_HOST=app_db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SERVER_PORT=8080
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
    volumes:
      - ./certs:/app/certs
    networks:
      - app-network
    depends_on:
      - app_db
    ports:
    - "8080:8080"
    restart: unless-stopped
  nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      environment:
        - DOMAIN
      depends_on:
        - matomo
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./etc/nginx/templates:/etc/nginx/templates:ro
        - ./etc/letsencrypt:/etc/letsencrypt:ro
        - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
              certonly --reinstall --webroot --webroot-path=/var/www/certbot
              --email ${EMAIL} --agree-tos --no-eff-email
              -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

volumes:
  mysql: ~

networks: 
  app-network:
