services:
  app_db:
    container_name: DrinkinggameDB
    image: mariadb:10
    environment:
      MYSQL_DATABASE: drinkinggame
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes: 
      - mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    networks: 
    - app-network 
    restart: unless-stopped
  app-backend:
    container_name: AppBackend
    image: ghcr.io/dasanten/drinkgame-backend:latest
    environment:
      - ACTIVE_PROFILE=prod
      - DATABASE_HOST=app_db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SERVER_PORT=8080
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
    volumes:
      - ./certs:/app/certs
    networks:
      - app-network
    depends_on:
      - app_db
    ports:
    - "8080:8080"
    restart: unless-stopped

volumes:
  mysql: ~

networks: 
  app-network: